module "store_write" {
  source  = "../ssm-parameter-store"

  count = var.ssm_enabled ? 1 : 0

  kms_arn         = var.kms_arn
  parameter_write = concat([
    {
      name        = "/AppSettings/ConnectionStrings/Default"
      value       = "Data Source=${local.instance_address};Initial Catalog=${local.db_name};Persist Security Info=True;User ID=${local.user};Password=${local.password};Application Name=${module.this.name};"
      type        = "SecureString",
      description = "${module.this.name} connection string for environment for CI/CD pipeline generated by Terraform."
    }
  ])

  context = module.this.context
}